Update terraform-deploy-template.yml

diff --git a/.github/workflows/terraform-deploy-template.yml b/.github/workflows/terraform-deploy-template.yml
--- a/.github/workflows/terraform-deploy-template.yml
+++ b/.github/workflows/terraform-deploy-template.yml
@@ -50,7 +50,14 @@ jobs:
 
       - name: Terraform Plan
         id: plan
-        run: terraform plan -lock=false -out=tfplan
+        run: |
+            terraform plan -out=tfplan
+            exitcode=$?
+            if [ $exitcode -eq 1 ]; then
+              echo "Terraform plan failed"
+              exit 1
+            fi
+            exit 0
         continue-on-error: true
         working-directory: ${{ inputs.working-directory }}
 
