Update terraform-deploy-envs-template.yml

diff --git a/.github/workflows/terraform-deploy-envs-template.yml b/.github/workflows/terraform-deploy-envs-template.yml
--- a/.github/workflows/terraform-deploy-envs-template.yml
+++ b/.github/workflows/terraform-deploy-envs-template.yml
@@ -59,16 +59,16 @@ jobs:
       #     echo "Testing clone:"
       #     git ls-remote https://github.com/ensembleanalytics/ensemble-terraform-aws-rds-aurora.git HEAD
 
-      - name: Configure Git credentials for private modules
-        env:
-          TF_GITHUB_PAT: ${{ secrets.TF_GITHUB_PAT }}
-        run: |
-          echo "PAT length: ${#TF_GITHUB_PAT}"
-          if [ -z "$TF_GITHUB_PAT" ]; then
-            echo "ERROR: TF_GITHUB_PAT is empty!"
-            exit 1
-          fi
-          git config --global url."https://${TF_GITHUB_PAT}@github.com/".insteadOf "https://github.com/"
+      # - name: Configure Git credentials for private modules
+      #   env:
+      #     TF_GITHUB_PAT: ${{ secrets.TF_GITHUB_PAT }}
+      #   run: |
+      #     echo "PAT length: ${#TF_GITHUB_PAT}"
+      #     if [ -z "$TF_GITHUB_PAT" ]; then
+      #       echo "ERROR: TF_GITHUB_PAT is empty!"
+      #       exit 1
+      #     fi
+      #     git config --global url."https://${TF_GITHUB_PAT}@github.com/".insteadOf "https://github.com/"
       ## DEBUGGING REMOVE AFTER TESTING ##
       
       - name: Setup Terraform
